---
title: "Trying pyABF"
author: "Christelinda Laureijs"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    css: "../Templates/my-CSS-theme.css"
  pdf_document:
    toc: true
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  dev = c("png"),
  dpi = 300,
  fig.align = "center",
  comment = NA,
  echo = T,
  message = F,
  warning = F
)
```

```{r load-r-libraries}
library(reticulate)
use_virtualenv("./Current_analysis")

library(ggplot2)
```

```{python load-py-libraries}
import seaborn as sns
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import numpy as np


import scipy
from scipy import signal
from scipy.signal import find_peaks
from scipy.optimize import curve_fit

```

```{r}
# Only run this once
#virtualenv_create("./Current_analysis")
#use_virtualenv("./Current_analysis")

#virtualenv_install("./Current_analysis",
 #                  packages = "Tcl")
#virtualenv_install("./Current_analysis",
#                   packages = "tk")
#virtualenv_install("./Current_analysis",
#packages = c("pandas","scikit-learn","seaborn"))

# Get list of current packages installed
#py_list_packages("./Current_analysis", type = "virtualenv")
```

```{python load-fmri-data}
fmri = sns.load_dataset("fmri")
```

```{r view-fmri-data}
head(py$fmri)
```

```{r subset-data}
f1 <- subset(py$fmri, region == "parietal")
```

```{python plot-frmi-data}
#sns.scatterplot(x = "timepoint", y = "signal", data=r.f1)

#plt.show()
#plt.clf()
```

```{r ggplot-equivalent}
ggplot(f1, aes(x = timepoint, y = signal)) +
  geom_point() +
  theme_minimal()
```


# Sinusoidal Wave


```{python create-dataframe-sine-wave}
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)



#plt.plot(t, s)

#plt.grid(True)
#plt.show()
#plt.clf()
```

```{r}
plot(py$t, py$s)
```

# Find peaks

```{r}
my_df <- read.csv("My-Sample-Peak-Data.csv")

```

```{python}
my_python_df = r.my_df
```

```{r}
plot(my_df)
```



```{r}
# from scipy.signal import find_peaks as fp

```

```{python}
height = 3


my_peaks, my_heights = find_peaks(x = my_python_df.p1, height = height)

```

```{r}
ggplot(my_df, aes(x = time, y = p1)) +
  geom_point() +
  geom_line() +
  #geom_point(aes(py$my_peaks, y = py$my_heights), color = "red") +
  theme_minimal()
```




```{r}
py$my_peaks
```


```{r}
py$my_heights
```


# pyABF

https://spikesandbursts.wordpress.com/2022/07/03/patch-clamp-data-analysis-in-python-postsynaptic-currents-and-potentials/


https://github.com/pypa/virtualenv/issues/93
